data:extend({
        {
            type = "int-setting",
            name = "tick-rate",
            setting_type = "startup",
            default_value = 30,
            order = "r",
        },
        {
            type = "int-setting",
            name = "scan-rate",
            setting_type = "startup",
            default_value = 180,
            order = "r",
        },
        {
            type = "int-setting",
            name = "t1-max-signals",
            setting_type = "startup",
            default_value = 30,
            order = "r",
        },
        {
            type = "int-setting",
            name = "t2-max-signals",
            setting_type = "startup",
            default_value = 75,
            order = "r",
        },
        {
            type = "int-setting",
            name = "t3-max-signals",
            setting_type = "startup",
            default_value = 200,
            order = "r",
        },
        {
            type = "int-setting",
            name = "t1-range",
            setting_type = "startup",
            default_value = 750,
            order = "r",
        },
        {
            type = "int-setting",
            name = "t2-range",
            setting_type = "startup",
            default_value = 1500,
            order = "r",
        },
        {
            type = "int-setting",
            name = "repeater-range",
            setting_type = "startup",
            default_value = 400,
            order = "r",
        },
        {
            type = "int-setting",
            name = "satellite-channels",
            setting_type = "startup",
            default_value = 40,
            order = "r",
        },
})
